spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  http:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379
naver:
  login-base-uri: null
  profile-base-url: null
payment:
  base-url: null
  success-url: null
  fail-url: null
sse:
  timeout: null
cloud:
  aws:
    credentials:
      access-key: null
      secret-key: null
    region:
      static: null
    s3:
      bucket: null
jwt:
  secret:  123213hdsfhsa8u717832jhdbvhjasbdf862637812y3dbhvbuysdahgf7612t1719h3esbf6atdfahsfuysah9ui32131231231233243214324324
  jwt.secret : 123213hdsfhsa8u717832jhdbvhjasbdf862637812y3dbhvbuysdahgf7612t1719h3esbf6atdfahsfuysah9ui322132132143124324234